drop table if exists TICKET, MATCHES, TEAM, FAN, STADIUM;

CREATE TABLE STADIUM (
STADIUMID CHAR(3) CONSTRAINT STADIUM_PK PRIMARY KEY,
STADIUMNAME VARCHAR(30),
STADIUMCITY VARCHAR(20),
CAPACITY INT check (CAPACITY>0),
OPENYEAR INT check (OPENYEAR>0 and OPENYEAR  < (extract(year from CURRENT_DATE) + 1))
);

CREATE TABLE FAN (
FANID CHAR(9) CONSTRAINT FAN_PK primary key,
FANNAME VARCHAR(25),
FANNATIONALITY VARCHAR(30),
FANCATEGORY CHAR(7)
);

CREATE TABLE TEAM (
TEAMID CHAR(4) constraint TEAM_PK primary key,
COUNTRY VARCHAR(20),
CONTINENT VARCHAR(15),
FIFARANK SMALLINT,
TEAMGROUP CHAR(1),
MANAGER VARCHAR(20),
NICKNAME VARCHAR(25)
);

CREATE TABLE MATCHES (
MATCHID CHAR(5),
FIRSTTEAM CHAR(4),
SECONDTEAM CHAR(4),
MATCHDATE DATE,
KICKOFF TIME,
STADIUMID CHAR(3),
constraint MATCHES_PK primary key (MATCHID),
constraint MATCHES_FK1 foreign key (FIRSTTEAM) references TEAM(TEAMID),
constraint MATCHES_FK2 foreign key (SECONDTEAM) references TEAM(TEAMID),
constraint MATCHES_FK3 foreign key (STADIUMID) references STADIUM(STADIUMID)
);

CREATE TABLE TICKET (
TICKETID CHAR(15),
BLOCKNO CHAR(4),
ROWNO CHAR(4),
SEATNO CHAR(4),
PRICE SMALLINT,
MATCHID CHAR(5),
FANID CHAR(9),
CONSTRAINT TICKET_PK PRIMARY KEY (TICKETID),
CONSTRAINT TICKET_FK1 FOREIGN KEY (MATCHID) REFERENCES MATCHES (MATCHID),
CONSTRAINT TICKET_FK2 FOREIGN KEY (FANID) REFERENCES FAN (FANID)
);

insert INTO stadium VALUES ('S01','LUZHNIKI STADIUM','MOSCOW',8000,1956);
insert INTO stadium VALUES ('S02','SAINT PETTERSBURG STADIUM','SAINT PETTERSBURG',67000,2017);
insert INTO stadium VALUES ('S03','FISHT STADIUM','SOCHI',48000,2013);
insert INTO stadium VALUES ('S04','KAZAN ARENA','KAZAN',45000,2013);
insert INTO stadium VALUES ('S05','SAMARA ARENA','SAMARA',45000,2018);
insert INTO stadium VALUES ('S06','SPARTAK STADIUM', 'MOSCOW',42000,2014);

insert into fan values ('F001','MONICA JONES','AMERICAN','SILVER');
insert into fan values ('F002','DMITRIY VLADIMIR','RUSSIAN','GOLD');
insert into fan values ('F003','ELLEN SMITH','AUSTRALIAN','SILVER');
insert into fan values ('F004','MR. BEAN','BRISTISH','GOLD');
insert into fan values ('F005','IGOR MIKHAIL','RUSSIAN','BRONZE');
insert into fan values ('F006','ALBERTO HERNANDEZ','BRAZILIAN','SILVER');
insert into fan values ('F007','NATAIA PAKLINA','RUSSIAN','BRONZE');
insert into fan values ('F008','NANCY AJRAM','LEBANESE', 'SILVER');
insert into fan values ('F009','JIE CHEN','CHINESE','GOLD');
insert into fan values ('F010','MAX CAMERON','AMERICAN','SILVER');

INSERT INTO TEAM VALUES ('T1','ARGENTINA','SOUTH AMERICA',5,'D','JORGE SAMPAOLI','WHITE AND SKY BLUES');
INSERT INTO TEAM VALUES ('T2','GERMANY','EUROPE',1,'F','JOACHIM LOW',NULL);
INSERT INTO TEAM VALUES ('T3','RUSSIA','ASIA',70,'A','STANISLAV CHERCHESOV','SBORNAYA (TEAM)');
INSERT INTO TEAM VALUES ('T4','SOUTH KOREA','ASIA',57,'F','SHIN TAE-YONG','ASIAN TIGERS');
INSERT INTO TEAM VALUES ('T5','SPAIN','EUROPE',10,'B','JULEN LOPETEGUI',NULL);
INSERT INTO TEAM VALUES ('T6','SWEDEN','EUROPE',24,'F','JANNE ANDERSSON',NULL);
INSERT INTO TEAM VALUES ('T7','SWITZERLAND','EUROPE',6,'E','VLADIMIR PETKOVIC','THE RED CRUSADERS');
INSERT INTO TEAM VALUES ('T8','TUNISIA','AFRICA',21,'G','NABIL MAALOUL','THE EAGLES OF CARTHAGE');
INSERT INTO TEAM VALUES ('T9','URUGUAY','SOUTH AMERICA',14,'A','OSCAR TABAREZ','CHARRUAS');
INSERT INTO TEAM VALUES ('T10','AUSTRALIA','OCEANS',36,'C','BERT VAN MARWIJK','SOCCEROOS');
INSERT INTO TEAM VALUES ('T11','BELGIUM','EUROPE',3,'G','ROBERTO MARTÃ�NEZ','RED DEVILS');
INSERT INTO TEAM VALUES ('T12','BRAZIL','SOUTH AMERICA',2,'E','TITEÂ ','THE SELECTION');
INSERT INTO TEAM VALUES ('T13','COLOMBIA','SOUTH AMERICA',16,'H','JOSE PEKERMAN','THE COFFEE GROWERS');
INSERT INTO TEAM VALUES ('T14','COSTA RICA','SOUTH AMERICA',23,'E',NULL,'LOS TICOS');
INSERT INTO TEAM VALUES ('T15','CROATIA','EUROPE',20,'D','ZLATKO DALICÂ ','THE BLAZERS');
INSERT INTO TEAM VALUES ('T16','DENMARK','EUROPE',12,'C','AGE HAREIDE','DANISH DYNAMITE');
INSERT INTO TEAM VALUES ('T17','EGYPT','AFRICA',45,'A','HECTOR CUPER','PHARAOHS');
INSERT INTO TEAM VALUES ('T18','ENGLAND','EUROPE',13,'G','GARETH SOUTHGATEÂ ','THREE LIONS');
INSERT INTO TEAM VALUES ('T19','FRANCE','EUROPE',7,'C','DIDIER DESCHAMPS','THE BLUES');
INSERT INTO TEAM VALUES ('T20','ICELAND','EUROPE',22,'D','HEIMIR HALLGRIMSSON','OUR BOYS');
INSERT INTO TEAM VALUES ('T21','IRAN','ASIA',37,'B','CARLOS QUEIROZ','TEAM MELLI');
INSERT INTO TEAM VALUES ('T22','JAPAN','ASIA',61,'H','VAHID HALILHODZIC','BLUE SAMURAI');
INSERT INTO TEAM VALUES ('T23','MEXICO','SOUTH AMERICA',15,'F','JUAN CARLOS OSORIOÂ ','EL TRICOLOR');
INSERT INTO TEAM VALUES ('T24','MOROCCO','AFRICA',41,'B','HERVE RENARD','ATLAS LIONS');
INSERT INTO TEAM VALUES ('T25','NIGERIA','AFRICA',48,'D','GERNOT ROHR','SUPER EAGLES');
INSERT INTO TEAM VALUES ('T26','PANAMA','SOUTH AMERICA',55,'G','HERNAN DARIO GOMEZ','THE RED TIDE');
INSERT INTO TEAM VALUES ('T27','PERU','SOUTH AMERICA',11,'C','RICARDO GARECA','LOS INCAS');
INSERT INTO TEAM VALUES ('T28','POLAND','EUROPE',8,'H','ADAM NAWALKA','THE POLISH EAGLES');
INSERT INTO TEAM VALUES ('T29','PORTUGAL','EUROPE',4,'B','FERNANDO SANTOS','TEAM OF THE CASTLES');
INSERT INTO TEAM VALUES ('T30','SAUDI ARABIA','ASIA',67,'A','BERT VAN MARWIJK','THE GREEN FALCONS');
INSERT INTO TEAM VALUES ('T31','SENEGAL','AFRICA',27,'H','ALIOU CISSE','THE LIONS OF TERANGA');
INSERT INTO TEAM VALUES ('T32','SERBIA','EUROPE',34,'E','MLADEN KRSTAJIC','THE EAGLES');

INSERT INTO MATCHES VALUES ('M01','T9','T17','2018-06-14','15:00:00','S01');
INSERT INTO MATCHES VALUES ('M02','T5','T29','2018-06-14','16:00:00','S02');
INSERT INTO MATCHES VALUES ('M03','T10','T19','2018-06-16','18:00:00','S03');
INSERT INTO MATCHES VALUES ('M04','T10','T16','2018-06-19','20:00:00','S02');
INSERT INTO MATCHES VALUES ('M05','T1','T15','2018-06-19','20:00:00','S04');
INSERT INTO MATCHES VALUES ('M06','T2','T4','2018-06-20','15:00:00','S06');
INSERT INTO MATCHES VALUES ('M07','T11','T19','2018-07-15','20:00:00','S01');
INSERT INTO MATCHES VALUES ('M08','T15','T19','2018-07-15','16:00:00','S02');

INSERT INTO ticket VALUES ('Tic1','A112',23,19,150,'M01','F001');
INSERT INTO ticket VALUES ('Tic10','D109',9,20,500,'M06','F009');
INSERT INTO ticket VALUES ('Tic2','B75',45,11,185,'M02','F003');
INSERT INTO ticket VALUES ('Tic3','D109',7,21,200,'M02','F005');
INSERT INTO ticket VALUES ('Tic4','B80',41,8,250,'M03','F001');
INSERT INTO ticket VALUES ('Tic5','E123',23,15,300,'M03','F004');
INSERT INTO ticket VALUES ('Tic6','A266',17,24,375,'M05','F002');
INSERT INTO ticket VALUES ('Tic7','B45',25,11,350,'M05','F009');
INSERT INTO ticket VALUES ('Tic8','F11',23,14,300,'M06','F007');
INSERT INTO ticket VALUES ('Tic9','C233',7,23,750,'M08','F001');



/*Q3*/
select MATCHID
FROM matches
WHERE KICKOFF > '16:00:00'
ORDER BY KICKOFF DESC;

/*Q4*/
SELECT LOWER(COUNTRY) as Country, LOWER(CONTINENT) as Continent
FROM TEAM
WHERE FIFARANK BETWEEN 2 AND 5;

/*Q5*/
SELECT TICKETID, BLOCKNO
FROM TICKET
WHERE BLOCKNO LIKE 'A%'OR BLOCKNO LIKE 'B%' ORDER BY BLOCKNO ASC;

/*Q6*/
SELECT CONCAT(MATCHID, ' starts at ', KICKOFF) "KICK OFF TIME"
FROM MATCHES
WHERE STADIUMID=(SELECT STADIUMID FROM STADIUM WHERE STADIUMNAME='KAZAN ARENA');

/*Q7*/
SELECT substring(COUNTRY,1,3) "COUNTRY INITIALS", MATCHDATE, KICKOFF
FROM TEAM, MATCHES
WHERE MATCHES.FIRSTTEAM=TEAM.TEAMID AND MATCHES.SECONDTEAM=TEAM.TEAMID
AND ( FIRSTTEAM IN (select TEAMID FROM TEAM WHERE MANAGER IS NULL)
OR SECONDTEAM IN (select TEAMID FROM TEAM WHERE MANAGER IS NULL) )
ORDER BY MATCHDATE DESC;

/*Q8*/
SELECT distinct TICKET.FANID, FAN.FANNAME
FROM TICKET INNER JOIN FAN ON TICKET.FANID=FAN.FANID;

/*Q9*/
SELECT FANID, FANNAME
FROM FAN
WHERE FANID IN (SELECT DISTINCT FANID FROM TICKET);

/*Q10 - count(1) or count(*) or count(fancategory)*/
SELECT DISTINCT FANCATEGORY, COUNT(1) "NUMBER OF TICKET PURCHASED", SUM(PRICE) "TOTAL PRICE"
FROM FAN, TICKET
WHERE FAN.FANID=TICKET.FANID GROUP BY FANCATEGORY;

/*Q11 != <> */
SELECT TICKET.MATCHID, COUNT(TICKETID) "NUMBER OF TICKET PURCHASED"
FROM TICKET, MATCHES 
WHERE TICKET.MATCHID=MATCHES.MATCHID 
AND MATCHES.STADIUMID IN (SELECT STADIUMID FROM STADIUM WHERE OPENYEAR != 2013)
GROUP BY TICKET.MATCHID HAVING COUNT(TICKETID) >1;

/*Q12*/
SELECT STADIUMNAME, COUNT(MATCHID) "NUMBER OF MATCHES"
FROM STADIUM, MATCHES
WHERE MATCHES.STADIUMID=STADIUM.STADIUMID
GROUP BY STADIUMNAME
ORDER BY COUNT(MATCHID) DESC LIMIT 2;

/*Q14*/
DROP VIEW IF EXISTS BRONZE;

create view bronze as
SELECT FANNAME, MATCHES.MATCHID, STADIUMNAME
FROM FAN natural join ticket natural join MATCHES natural JOIN STADIUM;

select * from bronze;
 
SELECT FANNAME, MATCHES.MATCHID, STADIUMNAME
FROM FAN 
inner join ticket using (fanid)
inner join MATCHES using (matchid)
inner JOIN STADIUM using (stadiumid);


/*Q15 - Procedures in PostgreSQL (Oracle, DB2) are not same like procedures in MS-SQL.*/
/*As the question was written specifically for MS-SQL, I'm using (converting it to) postgreSQL so I've made it a function.*/


drop function if exists FANMATCHES(in NAME_OF_FAN VARCHAR(25));

create FUNCTION FANMATCHES(in NAME_OF_FAN VARCHAR(25))
returns TABLE(MATCHID CHAR(5), STADNAME VARCHAR(30), SEAT CHAR(4), KICKOFFTIME TIME)
language 'plpgsql'
as $BODY$
begin 
return QUERY SELECT MATCHES.MATCHID, STADIUMNAME, SEATNO, KICKOFF
FROM FAN natural join ticket natural join MATCHES natural JOIN STADIUM
WHERE FANNAME=NAME_OF_FAN;
end;
$BODY$;

SELECT FANMATCHES('MONICA JONES') ;



/*Q13*/
/*using join*/ 

SELECT A.COUNTRY, 

	case 
		when POSITION(' ' in A.MANAGER)!=0
		then CONCAT(SUBSTRING(A.MANAGER,1,1),'. ',SUBSTRING(A.MANAGER,POSITION(' ' in A.MANAGER)+1,20),CONCAT(SUBSTR(A.MANAGER,1,1),'.'))
	end
	as "MANAGER INITIALS"

, B.COUNTRY, 

	case 
		when POSITION(' ' in B.MANAGER)!=0
		then CONCAT(SUBSTRING(B.MANAGER,1,1),'. ',SUBSTRING(B.MANAGER,POSITION(' ' in B.MANAGER)+1,20), CONCAT(SUBSTRING(B.MANAGER,1,1),'.'))
	end
	as "MANAGER INITIALS"

FROM TEAM A inner JOIN MATCHES ON A.TEAMID=MATCHES.FIRSTTEAM
inner JOIN TEAM B ON B.TEAMID=MATCHES.SECONDTEAM
AND (FIRSTTEAM IN (SELECT TEAMID FROM TEAM WHERE COUNTRY='CROATIA')
OR SECONDTEAM IN (SELECT TEAMID FROM TEAM WHERE COUNTRY='CROATIA'));



/*not using join*/

SELECT A.COUNTRY, 

	case 
		when POSITION(' ' in A.MANAGER)!=0
		then CONCAT(SUBSTRING(A.MANAGER,1,1),'. ',SUBSTRING(A.MANAGER,POSITION(' ' in A.MANAGER)+1,20),CONCAT(SUBSTR(A.MANAGER,1,1),'.'))
	end
	as "MANAGER INITIALS"

, B.COUNTRY, 

	case 
		when POSITION(' ' in B.MANAGER)!=0
		then CONCAT(SUBSTRING(B.MANAGER,1,1),'. ',SUBSTRING(B.MANAGER,POSITION(' ' in B.MANAGER)+1,20), CONCAT(SUBSTRING(B.MANAGER,1,1),'.'))
	end
	as "MANAGER INITIALS"
FROM TEAM A, TEAM B
WHERE (A.TEAMID, B.TEAMID) IN (
SELECT FIRSTTEAM, SECONDTEAM FROM MATCHES WHERE
(FIRSTTEAM IN (SELECT TEAMID FROM TEAM WHERE COUNTRY='CROATIA'))
OR (SECONDTEAM IN (SELECT TEAMID FROM TEAM WHERE COUNTRY='CROATIA')));



